# -*- coding: utf-8 -*-
"""transcriber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKKupND_rtf2zZFppIu4WRyOE5xCdDyD

# **1. Install Whisper and Dependencies**
"""

!pip install -q git+https://github.com/openai/whisper.git
!sudo apt update -q > /dev/null 2>&1 && sudo apt install ffmpeg -y > /dev/null 2>&1

"""# **2. Install modules** **testo in grassetto**"""

import os
import zipfile
from google.colab import files
import whisper

"""# **3. Upload Audio Files**"""

print("-----START-----")
print("Upload the audio files you want to transcribe.\n")
uploaded_files = files.upload()

"""# **4. Create a Directory for Transcriptions**"""

output_dir = "./transcriptions/"
os.makedirs(output_dir, exist_ok=True)

"""#**5. Load Whisper Model**"""

model = whisper.load_model("large")

"""# **6. Automatic Processing of Audio Files**"""

audio_files = [file for file in uploaded_files.keys() if file.lower().endswith(('.wav', '.mp3', '.m4a'))]

for audio_file in audio_files:
    print(f"Transcribing: {audio_file}")
    result = model.transcribe(audio_file)
    output_file = os.path.join(output_dir, os.path.splitext(audio_file)[0] + ".txt")
    with open(output_file, "w") as f:
        f.write(result["text"])
    print(f"Transcription completed: {output_file}\n")

print("All transcriptions have been completed!")

"""# **7. Create a ZIP Archive for Transcribed Files**"""

zip_filename = input("Enter a name for the ZIP file (without extension): ") + ".zip"

with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for root, dirs, files_list in os.walk(output_dir):
        for file in files_list:
            zipf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), output_dir))

"""# **8. Download the ZIP Archive**"""

print("Preparing download...")
files.download(zip_filename)
print("-----END-----")
