# -*- coding: utf-8 -*-
"""transcriber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKKupND_rtf2zZFppIu4WRyOE5xCdDyD
"""

import os
import zipfile
from google.colab import files  # For handling file uploads and downloads

# **1. Install Whisper and Dependencies**
# Install Whisper and required dependencies
!pip install -q git+https://github.com/openai/whisper.git
!sudo apt update -q > /dev/null 2>&1 && sudo apt install ffmpeg -y > /dev/null 2>&1

# **2. Upload Audio Files**
print("\n-----START-----")
print("Upload the audio files you want to transcribe.")
uploaded_files = files.upload()  # Allows manual file uploads

# **3. Create a Directory for Transcriptions**
output_dir = "./transcriptions/"
os.makedirs(output_dir, exist_ok=True)

# **4. Automatic Processing of Audio Files**
import whisper
model = whisper.load_model("large")  # Load the Whisper "large" model

# Filter uploaded files to keep only supported audio formats
audio_files = [file for file in uploaded_files.keys() if file.lower().endswith(('.wav', '.mp3', '.m4a'))]

for audio_file in audio_files:
    print(f"Transcribing: {audio_file}")

    # Transcription using Whisper
    result = model.transcribe(audio_file)

    # Save transcription to a .txt file
    output_file = os.path.join(output_dir, os.path.splitext(audio_file)[0] + ".txt")
    with open(output_file, "w") as f:
        f.write(result["text"])

    print(f"Transcription completed: {output_file}")

print("All transcriptions have been completed!")

# **5. Create a ZIP Archive for Transcribed Files**
# User input for ZIP filename
zip_filename = input("Enter a name for the ZIP file (without extension): ") + ".zip"

with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for root, dirs, files_list in os.walk(output_dir):
        for file in files_list:
            zipf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), output_dir))

# **6. Download the ZIP Archive**
print("Preparing download...")
files.download(zip_filename)  # Allows the user to download the ZIP file
print("-----END-----")